{% set name = "torchtuples" %}
{% set version = "0.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0c7fe69977eb594fd9e81015821bb62c849be94d378bd072bdcb08cd68fffc3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=3.0.3
    - numpy >=1.15.4
    - pandas >=0.24.2
    - python >=3.6
    - pytorch >=1.7

test:
  imports:
    - torchtuples
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/havakv/torchtuples
  summary: Training neural networks in PyTorch
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
